version: '3.4'

x-env: &env
    POSTGRES_DB: "transcendence"
    POSTGRES_USER: "postgres"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/usr/src/app
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
      DISABLE_PIP_VERSION_CHECK: 1
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      <<: *env
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.5-bookworm
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      <<: *env
    env_file:
      - .env
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/data:/var/lib/postgresl/data
      - ./postgres/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080


  # pgadmin:
  #   image: dpage/pgadmin4:8.0
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@localhost.de"
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   ports:
  #     - 127.0.0.1:8080:80
