version: '3'

services:
  postgres:
    image: postgres:15.5-bookworm
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "transcendence"
      POSTGRES_USER: "postgres"
    env_file:
      - .env
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/data:/var/lib/postgresl/data
      - ./postgres/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
